---
title: "Cluster Exploration on Actual Data"
author: "Tom Helmuth, Nic McPhee"
date: "March 2, 2015"
output: 
  html_document:
    toc: true
---

# Import the data

```{r}
# setwd("~/Documents/R/Clustering/lexicase-clusturing-analysis")
# 
# data1 <- read.csv("data/RSWN/lexicase/data1.csv")
# 
# columns_to_drop = c("uuid", "parent.uuids", "genetic.operators", "push.program.size", "plush.genome.size", "push.program", "plush.genome", "total.error")
# 
# data1 = data1[,!(names(data1) %in% columns_to_drop)]
# 
#write.csv(data1, "data/RSWN/lexicase/errors1.csv", row.names = FALSE)
```

Now, read errors data.

```{r}
#errors1 <- read.csv("data/RSWN/lexicase/errors1.csv")
```


# Calculate the number of clusters in a generation

Make some helper functions.

```{r}
# Takes error data (including generation and location columns) and a generation, and 
extract_clustering_data = function(data, gen){
  
  print(sprintf("Generation %i", gen))
  
  this_gen_data = subset(data, generation == gen)
  
  columns_to_drop = c("generation", "location")
  right_rows = this_gen_data[,!(names(this_gen_data) %in% columns_to_drop)]
  
  return(right_rows)
}

elitize_generation_data = function(gen_data){
  result <- gen_data
  for (i in 1:length(gen_data)) {
    result[i] <- ifelse(gen_data[i] == min(gen_data[i]), 1, 0)
    }
  
  return(result)
}

count_clusters = function(clustering_data, height) {
  agnes_results <- agnes(clustering_data, metric = "manhattan")
  num_clusters <- sum(agnes_results$height>height) + 1
  
  #plot(agnes_results, which.plots=2)
  
  print(sprintf("  Number of clusters is: %i\n", num_clusters))
  
  return(num_clusters)
}

num_clusters_for_all_gens = function(data, height, normalization_fn){
  num_gens = max(data$generation)
  num_clusters <- sapply(seq(0, num_gens),
                         function(gen){
                           count_clusters(normalization_fn(extract_clustering_data(data, gen)),
                                          height)
                           }
                         )
  
  return(num_clusters)
}
```

Get the count of the number of clusters per generation. Took about 4 minutes for this dataset with 129 generations.

```{r}
# This is slow
# cluster_count <- num_clusters_for_all_gens(errors1, 20, elitize_generation_data)

# The result is the same as this, for errors1, height 20
cluster_count = c(5,7,11,11,11,13,15,15,27,29,42,41,40,49,46,33,28,31,34,31,27,30,31,31,27,23,20,27,24,29,20,21,26,23,23,22,23,21,20,29,23,21,17,20,25,23,24,23,27,24,16,27,22,25,19,22,28,20,23,22,22,22,23,20,23,27,25,25,23,26,19,28,24,23,29,24,22,25,21,21,18,21,20,23,21,20,23,22,24,28,34,28,27,25,29,26,26,20,23,25,28,25,30,26,23,26,34,29,25,21,29,29,25,30,31,22,39,34,33,35,30,27,23,18,29,27,24,26,22,17)

plot(cluster_count)
```


